#!/usr/bin/env python3
"""Copy the durable subset of the latest successful case run into docs/design/results/<case>/
and generate SUMMARY.md tables from the run data (so reports cannot drift from outputs).

    python scripts/make_design_snapshot.py pd1-jm85 dp2-prescribed baseline-250N

Refuses to snapshot a case whose LATEST.json is marked failed or whose run folder is missing.
"""
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KEEP = ['manifest.json', 'run_metadata.json', 'run.log', 'station_table.csv', 'operating_line.csv', 'pressure_ledger.csv',
        'power_ledger.json', 'limits.json', 'candidate_checks.json', 'design_point.json', 'diffuser.json', 'nozzle.json',
        'clearances.json', 'structures.json', 'assembly_stack.json', 'seed_provenance.json', 'assumptions_register.json',
        'map_consistency.json', 'bom/candidate_bom.csv', 'bom/cost_summary.json', 'cad/cad_bundle.json',
        'cad/cad_parameters.csv', 'systems/fuel_budget.json', 'systems/starter_budget.json',
        'systems/electrical_budget.json', 'robustness/robustness.csv', 'robustness/robustness.json',
        'figures/cross_section.png', 'figures/compressor_map_operating_line.png', 'figures/campbell.png',
        'figures/unbalance_response.png', 'figures/operating_line.png', 'figures/robustness_tornado.png',
        'figures/cross_section.svg']
KEEP += ['combustor.json', 'rotordynamics.json', 'operating_line.json', 'design_readiness.json', 'systems/signals.json']


def fmt(v, nd=3):
    if v is None:
        return '-'
    if isinstance(v, bool):
        return 'yes' if v else 'no'
    if isinstance(v, (int, float)):
        if v != 0 and (abs(v) >= 1e5 or abs(v) < 1e-2):   # keeps e.g. 1.4 ms vs 1.2 ms distinguishable
            return f'{v:.4g}'
        return f'{v:,.{nd}f}'.rstrip('0').rstrip('.') if isinstance(v, float) else str(v)
    return str(v)


def table(rows, cols, heads=None):
    heads = heads or cols
    out = ['| ' + ' | '.join(heads) + ' |', '|' + '|'.join(['---'] * len(cols)) + '|']
    for r in rows:
        out.append('| ' + ' | '.join(fmt(r.get(c)) for c in cols) + ' |')
    return '\n'.join(out)


def summarize(case, src, dst):
    m = json.loads((src / 'manifest.json').read_text(encoding='utf-8'))
    L = ['# ' + case + ' - generated run summary', '',
         f'Generated by `scripts/make_design_snapshot.py` from `{src.relative_to(ROOT).as_posix()}`. '
         f'Design fingerprint `{m["design_fingerprint"][:12]}`. {m["release_status"]}.', '']
    lim = json.loads((src / 'limits.json').read_text(encoding='utf-8'))
    L += ['## Existing numerical screens (config/limits.yaml)', '',
          table(lim, ['status', 'label', 'value', 'operator', 'limit']), '']
    if (src / 'candidate_checks.json').exists():
        cc = json.loads((src / 'candidate_checks.json').read_text(encoding='utf-8'))
        L += ['## Candidate checks', '', table(cc, ['status', 'name', 'value', 'criterion', 'unit', 'reason']), '']
    if (src / 'operating_line.csv').exists():
        import csv
        rows = list(csv.DictReader(open(src / 'operating_line.csv', encoding='utf-8')))
        for r in rows:
            for k, v in list(r.items()):
                try:
                    r[k] = float(v)
                except (TypeError, ValueError):
                    pass
        L += ['## Fixed-geometry operating line (zero starter torque)', '',
              table(rows, ['N_rpm', 'status', 'beta', 'mdot_air_kg_s', 'PR', 'eta_c', 'SM_flow', 'T04_K', 'EGT_T5_K',
                           'eta_t_tt', 'ngv_flow_frac', 'fuel_kg_h', 'thrust_N', 'r_mass', 'r_power', 'map_conf']), '']
    if (src / 'station_table.csv').exists():
        import csv
        rows = list(csv.DictReader(open(src / 'station_table.csv', encoding='utf-8')))
        for r in rows:
            for k in ('T_total_K', 'P_total_Pa', 'T_static_K', 'P_static_Pa', 'mass_flow_kg_s'):
                r[k] = float(r[k]) if r.get(k) not in (None, '') else None
        L += ['## Design-point station table', '', table(rows, ['station', 'description', 'T_total_K', 'P_total_Pa',
                                                                 'T_static_K', 'P_static_Pa', 'mass_flow_kg_s', 'source']), '']
    if (src / 'robustness/robustness.json').exists():
        rb = json.loads((src / 'robustness/robustness.json').read_text(encoding='utf-8'))
        L += ['## Robustness cases (fixed geometry)', '',
              'Status rule: `fails` = no steady match or a physical screen exceeded; `unresolved` = the only issue is '
              'a model used outside its validity domain (map domain, map confidence, turbine loss-correlation range); '
              '`feasible` = every implemented screen and validity flag passed. `model_validity` lists validity flags '
              'even on failed points.', '',
              table(rb['cases'], ['N_rpm', 'status', 'case', 'T04_K', 'dT04_K', 'SM_flow', 'thrust_N', 'first_failure',
                                  'model_validity']), '',
              '### Single-parameter feasibility boundaries (design speed)', '',
              'Boundaries of the physical screens (match, T04, surge margin, choke); model validity on the feasible '
              'side of each boundary is reported separately.', '',
              table(rb['thresholds'], ['parameter', 'unit', 'boundary', 'feasible_side', 'failure_beyond',
                                       'model_validity_at_boundary', 'result']), '',
              '### Nozzle trim table (design speed)', '',
              table(rb['nozzle_trim_table'], ['ngv_exit_angle_deg', 'ngv_throat_m2', 'nozzle_exit_d_m', 'T04_K', 'thrust_N',
                                              'SM_flow', 'status', 'screen']), '',
              '### Combined-adverse rescue by nozzle area', '', '```json', json.dumps(rb['combined_adverse_rescue'], indent=1),
              '```', '', '### Alternative stage (JETMAX TW70 + NGV70 finished)', '',
              table(rb['alternative_candidate']['points'], ['nozzle_exit_d_m', 'N_rpm', 'status', 'T04_K', 'thrust_N',
                                                            'SM_flow', 'rotor_frac', 'first_failure']), '']
    if (src / 'bom/cost_summary.json').exists():
        cs = json.loads((src / 'bom/cost_summary.json').read_text(encoding='utf-8'))
        sc = cs['scenarios']
        rows = [dict(scenario=k, **v) for k, v in sc.items() if isinstance(v, dict) and 'total' in v]
        L += ['## Cash estimate (USD, all lines forecast)', '',
              table(rows, ['scenario', 'direct', 'freight', 'tax', 'reserve', 'total']), '',
              table(sc['options'], ['id', 'description', 'direct_or_tax_saving_usd', 'confirmed', 'consequence', 'dependency']),
              '']
    if (src / 'map_consistency.json').exists():
        mc = json.loads((src / 'map_consistency.json').read_text(encoding='utf-8'))
        L += ['## Prescribed point on the proxy map', '', '```json', json.dumps({k: v for k, v in mc.items()
                                                                                if k != 'speeds_passing_prescribed_flow'},
                                                                               indent=1), '```', '']
    (dst / 'SUMMARY.md').write_text('\n'.join(L) + '\n', encoding='utf-8')


def main(cases):
    for case in cases:
        latest = ROOT / 'out' / case / 'LATEST.json'
        if not latest.exists():
            raise SystemExit(f'{case}: no LATEST.json; run python run_case.py {case} first')
        info = json.loads(latest.read_text(encoding='utf-8'))
        if info.get('status') != 'success':
            raise SystemExit(f'{case}: latest run is marked {info.get("status")}; refusing to snapshot a stale result')
        src = ROOT / 'out' / info['run_dir']
        sys.path.insert(0, str(ROOT))
        from core import cases as C
        k = C.load_case(case)
        man = json.loads((src / 'manifest.json').read_text(encoding='utf-8'))
        current = C.case_fingerprint(k, C.case_records(k), extra=man.get('run_options'))
        if current != man['design_fingerprint']:
            raise SystemExit(f'{case}: latest run {man["design_fingerprint"][:12]} is STALE (current design '
                             f'{current[:12]}); rerun python run_case.py {case} first')
        dst = ROOT / 'docs' / 'design' / 'results' / case
        if not dst.resolve().is_relative_to((ROOT / 'docs/design/results').resolve()):
            raise SystemExit('snapshot destination escapes results directory')
        from core.records import file_sha256
        for rel in KEEP:
            p = src / rel
            # The manifest is the index that contains generated-file hashes; it
            # deliberately cannot contain a hash of itself.  Validate every
            # other retained artifact against that index.
            if rel == 'manifest.json':
                continue
            listed = man.get('generated_files', {}).get(rel)
            if p.exists() and file_sha256(p) != listed:
                raise SystemExit(f'{case}: output hash mismatch or untracked output: {rel}; rerun before snapshotting')
            # A listed output that has gone missing would silently drop a SUMMARY section
            # (e.g. robustness) while the old results folder is deleted below.
            if not p.exists() and listed is not None:
                raise SystemExit(f'{case}: output listed in the manifest is missing: {rel}; rerun before snapshotting')
        if dst.exists():
            shutil.rmtree(dst)
        dst.mkdir(parents=True)
        for rel in KEEP:
            p = src / rel
            if p.exists():
                q = dst / rel
                q.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(p, q)
        summarize(case, src, dst)
        print(f'{case}: snapshot of {info["run_dir"]} -> {dst.relative_to(ROOT).as_posix()}')


if __name__ == '__main__':
    main(sys.argv[1:] or ['pd1-jm85', 'dp2-prescribed', 'baseline-250N'])
